"""
generate_flow_prompts.py
Generates ready-to-paste JSON prompts for Google Flow (Veo 3), grounded
in the actual script, with an explicit audio-overlay mapping since Flow
only generates visuals.

Generated in BATCHES of a few chunks per LLM call — a single call for the
full 10-chunk array was too large and got truncated/empty on free-tier
token limits. The first batch's main_subject.type and visual_style.colors
are "locked" and reused verbatim in every later batch, so consistency
across the whole video is preserved even though it's built in pieces.
"""

import json
from llm_client import call_llm, clean_json_text

BATCH_SIZE = 3

FLOW_SYSTEM_PROMPT_TEMPLATE = """Act as an expert AI Video Producer and Prompt Engineer for advanced 3D video generation models (Google Flow / Veo 3).

You will be given the topic "{topic}" and {num_chunks_in_batch} sequential 10-second time window(s) (out of {total_chunks} total in the whole video). For EACH time window, generate one detailed, structured JSON prompt for a high-quality 3D explainer scene, optimized for 9:16 vertical format.

Strictly follow these rules:
1. Output ONLY a valid JSON array containing exactly {num_chunks_in_batch} object(s) — no markdown fences, no commentary before or after.
2. Each object represents exactly 10 seconds, structured into exactly 3 rapid scene sequences that together explain that window's content within exactly 10 seconds.
3. Keep explanations SHORT, SIMPLE, and VISUAL — strip jargon, focus on striking, easy-to-grasp visual concepts.
4. Visual tone: futuristic, highly detailed, cinematic — fast-paced high-end science documentary mixed with Pixar-quality CGI.
5. CONSISTENCY: {consistency_instruction}
6. Each chunk's scene_sequence and text_overlay MUST accurately depict and match the specific narration content given for that chunk below.
7. NO DIALOGUE, NO SPOKEN VOICE, NO NARRATION generated by Flow itself — the real voiceover is added separately afterward. Every environment/effects field must describe ONLY non-verbal sound (whooshes, clanks, ambient drone, impacts) and explicitly state "no dialogue, no voice, ambient sound effects only".

Use this exact JSON object structure for every chunk:
{{
  "video_type": "cinematic educational 3D [insert niche] animation",
  "topic": "{topic} Explained Simply",
  "duration": "10 seconds",
  "aspect_ratio": "9:16",
  "style": "hyper realistic CGI visualization",
  "quality": "ultra detailed 4K",
  "camera_style": "rapid cinematic dynamic camera movements",
  "environment": {{
    "background": "dark futuristic educational environment",
    "lighting": "vibrant volumetric glows with realistic subject highlights",
    "atmosphere": "Scientific documentary meets high-end cinematic animation, no dialogue, no voice, ambient sound effects only"
  }},
  "main_subject": {{
    "type": "[describe the main model or object being shown]",
    "pose": "[starting pose or framing for THIS chunk]",
    "visibility": "[transparency, glowing parts, or cross-sections for THIS chunk]"
  }},
  "scene_sequence": [
    {{
      "scene": 1,
      "title": "[Simple Scene Title]",
      "duration": "[e.g., 3 seconds]",
      "animation": "[what moves, matching this chunk's narration]",
      "camera": "[camera shot type]",
      "effects": ["[non-verbal sound/visual effect 1]", "[non-verbal effect 2]"],
      "text_overlay": "[Very short, punchy text matching this chunk's on-screen text]"
    }}
  ],
  "visual_style": {{
    "colors": ["[Hex Color 1]", "[Hex Color 2]", "[Hex Color 3]"],
    "graphics": "interactive infographic style",
    "motion_graphics": true,
    "floating_labels": true,
    "animated_arrows": true
  }},
  "render_keywords": [
    "Pixar quality CGI", "scientific documentary visuals", "hyper realistic textures",
    "cinematic educational graphics", "3D animation", "fast-paced fluid motion",
    "easy to understand visual breakdown", "no dialogue, sound effects only"
  ]
}}
"""


def _group_into_chunks(script, seconds_per_segment, chunk_seconds=10):
    segments_per_chunk = chunk_seconds // seconds_per_segment
    segs = script["segments"]
    return [segs[i:i + segments_per_chunk] for i in range(0, len(segs), segments_per_chunk)]


def _describe_chunk_for_grounding(chunk_index, chunk_segments):
    lines = [f"--- Chunk {chunk_index + 1} (narration content to match visually) ---"]
    for seg in chunk_segments:
        lines.append(
            f"Seg {seg['seg']} [{seg.get('emotion', 'authoritative')}]: "
            f'VO: "{seg["vo"]}" | On-screen text: "{seg["on_screen_text"]}" | '
            f'Intended visual: {seg["visual_prompt"]}'
        )
    return "\n".join(lines)


def _generate_batch(topic, chunk_batch, batch_start_index, total_chunks, style_lock):
    if style_lock is None:
        consistency_instruction = (
            "This is the FIRST batch — establish a main_subject.type and visual_style.colors "
            "that will represent the ENTIRE video. Choose something specific and reusable."
        )
    else:
        consistency_instruction = (
            f"Use EXACTLY this main_subject.type in every chunk: \"{style_lock['type']}\". "
            f"Use EXACTLY these visual_style.colors in every chunk: {json.dumps(style_lock['colors'])}. "
            "Only vary pose/animation/camera per chunk — do not invent a new subject or palette."
        )

    system_prompt = FLOW_SYSTEM_PROMPT_TEMPLATE.format(
        topic=topic,
        num_chunks_in_batch=len(chunk_batch),
        total_chunks=total_chunks,
        consistency_instruction=consistency_instruction,
    )

    grounding_blocks = [
        _describe_chunk_for_grounding(batch_start_index + i, chunk)
        for i, chunk in enumerate(chunk_batch)
    ]
    user_prompt = (
        f'Topic: "{topic}"\n\n'
        "Narration for this batch's time window(s):\n\n" + "\n\n".join(grounding_blocks)
    )

    raw = call_llm(system_prompt, user_prompt, json_mode=True)
    batch_prompts = json.loads(clean_json_text(raw))

    if not isinstance(batch_prompts, list):
        batch_prompts = batch_prompts.get("prompts") or batch_prompts.get("chunks") or [batch_prompts]

    return batch_prompts


def generate_flow_prompts(topic, script, config):
    seconds_per_segment = config["script"]["seconds_per_segment"]
    chunks = _group_into_chunks(script, seconds_per_segment, chunk_seconds=10)
    total_chunks = len(chunks)

    all_prompts = []
    style_lock = None

    for batch_start in range(0, total_chunks, BATCH_SIZE):
        chunk_batch = chunks[batch_start:batch_start + BATCH_SIZE]
        try:
            batch_prompts = _generate_batch(topic, chunk_batch, batch_start, total_chunks, style_lock)
        except Exception as e:
            print(f"[generate_flow_prompts] Batch starting at chunk {batch_start + 1} failed ({e}), skipping this batch")
            continue

        if style_lock is None and batch_prompts:
            first = batch_prompts[0]
            style_lock = {
                "type": first.get("main_subject", {}).get("type", ""),
                "colors": first.get("visual_style", {}).get("colors", []),
            }
            print(f"[generate_flow_prompts] Style locked: subject='{style_lock['type']}', colors={style_lock['colors']}")

        all_prompts.extend(batch_prompts)
        print(f"[generate_flow_prompts] Generated batch: chunks {batch_start + 1}-{batch_start + len(chunk_batch)}")

    if not all_prompts:
        raise RuntimeError("All Flow prompt batches failed — no prompts generated")

    if len(all_prompts) != total_chunks:
        print(f"[generate_flow_prompts] WARNING: expected {total_chunks} chunks, got {len(all_prompts)}")

    return all_prompts


def write_flow_prompts_file(flow_prompts, script, config, out_path="output/google_flow_prompts.txt"):
    seconds_per_segment = config["script"]["seconds_per_segment"]
    chunks = _group_into_chunks(script, seconds_per_segment, chunk_seconds=10)

    lines = [
        "GOOGLE FLOW PROMPTS — paste each block below into Google Flow, ONE AT A TIME, in order.",
        "",
        "*** IMPORTANT — READ THIS BEFORE YOU START ***",
        "Google Flow (Veo) only generates VISUALS + non-verbal SFX from these JSON prompts.",
        "It is instructed to generate NO dialogue/voice of its own. The real hook, explanation,",
        "and emotion only exist in the separate humanized voiceover audio files",
        "(voiceovers.zip, also uploaded to this Drive folder).",
        "",
        "TO GET A PROPER VIDEO, DO THIS MANUAL ASSEMBLY STEP:",
        "1. Generate each 10-second clip below in Flow, download them in order.",
        "2. In a video editor (CapCut/Clipchamp/etc), lay the Flow clips out in sequence.",
        "3. Keep Flow's own ambient SFX track (no voice was requested), just don't let it",
        "   overpower the real voiceover.",
        "4. Unzip voiceovers.zip and place seg_01.mp3, seg_02.mp3, etc. on the timeline in",
        "   order, back to back — see the per-chunk mapping below for which files match which",
        "   10-second block.",
        "5. Add the on-screen text overlays from metadata.txt as actual text layers.",
        "6. Optionally layer the ambience track under everything at low volume.",
        "",
        "Each block generates a 10-second clip. Google Flow (Veo 3) requires a Google account",
        "and, beyond the free monthly allowance, a paid Google AI Pro/Ultra plan.",
        "=" * 70,
    ]

    for i, prompt in enumerate(flow_prompts, start=1):
        chunk_segs = chunks[i - 1] if i - 1 < len(chunks) else []
        audio_files = ", ".join(f"seg_{seg['seg']:02d}.mp3" for seg in chunk_segs)
        emotions = ", ".join(f"{seg['seg']}={seg.get('emotion', 'authoritative')}" for seg in chunk_segs)

        lines.append(f"\n--- PROMPT {i} of {len(flow_prompts)} (seconds {(i-1)*10}-{i*10}) ---")
        lines.append(f"Overlay these audio files here, in order: {audio_files}")
        lines.append(f"Emotion per segment (for your own reference while editing pacing): {emotions}")
        lines.append("")
        lines.append(json.dumps(prompt, indent=2))

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"[generate_flow_prompts] Wrote {len(flow_prompts)} prompts -> {out_path}")
    return out_path


if __name__ == "__main__":
    print("Run via main.py — this module expects a generated script.")
